2022-12-07 00:04:01,417 INFO    MainThread:2685956 [wandb_setup.py:_flush():68] Configure stats pid to 2685956
2022-12-07 00:04:01,417 INFO    MainThread:2685956 [wandb_setup.py:_flush():68] Loading settings from /home/dongheng/.config/wandb/settings
2022-12-07 00:04:01,417 INFO    MainThread:2685956 [wandb_setup.py:_flush():68] Loading settings from /home/dongheng/LLMR/wandb/settings
2022-12-07 00:04:01,417 INFO    MainThread:2685956 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-07 00:04:01,418 INFO    MainThread:2685956 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'plot.py', 'program': 'plot.py'}
2022-12-07 00:04:01,418 INFO    MainThread:2685956 [wandb_init.py:_log_setup():476] Logging user logs to /home/dongheng/LLMR/wandb/run-20221207_000401-22gc4n5r/logs/debug.log
2022-12-07 00:04:01,418 INFO    MainThread:2685956 [wandb_init.py:_log_setup():477] Logging internal logs to /home/dongheng/LLMR/wandb/run-20221207_000401-22gc4n5r/logs/debug-internal.log
2022-12-07 00:04:01,419 INFO    MainThread:2685956 [wandb_init.py:init():516] calling init triggers
2022-12-07 00:04:01,419 INFO    MainThread:2685956 [wandb_init.py:init():520] wandb.init called with sweep_config: {}
config: {}
2022-12-07 00:04:01,419 INFO    MainThread:2685956 [wandb_init.py:init():569] starting backend
2022-12-07 00:04:01,419 INFO    MainThread:2685956 [wandb_init.py:init():573] setting up manager
2022-12-07 00:04:01,430 INFO    MainThread:2685956 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-12-07 00:04:01,437 INFO    MainThread:2685956 [wandb_init.py:init():580] backend started and connected
2022-12-07 00:04:01,444 INFO    MainThread:2685956 [wandb_init.py:init():658] updated telemetry
2022-12-07 00:04:01,459 INFO    MainThread:2685956 [wandb_init.py:init():694] communicating run to backend with 60 second timeout
2022-12-07 00:04:04,514 WARNING MsgRouterThr:2685956 [router.py:message_loop():77] message_loop has been closed
2022-12-07 00:04:11,478 ERROR   MainThread:2685956 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/dongheng/.conda/envs/LLMR/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/dongheng/.conda/envs/LLMR/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 698, in init
    timeout=self.settings.init_timeout, on_progress=self._on_progress_init
  File "/home/dongheng/.conda/envs/LLMR/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
